spring:
  application:
    name: SpringRESTClient3

server:
  port: 7091

opentracing:
  jaeger:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "prometheus"]